from utils import generate_schedule
import pandas as pd
import os
from datetime import date

def main():
    # 員工名單
    employees = ['芷芸','婷瑩','冠汝','芬萍','勇得','婉霏','鈺姍','欣怡',
                 '文雄','詣勛','俊穎','琦葳','乙玲','宛淇','惠琳','丁丁']

    # 呼叫 utils.py 產生班表紀錄：list of dicts
    schedule_records = generate_schedule(employees, weeks=1)

    # 轉為 DataFrame → 員工 x 日期 的橫向班表格式
    df = pd.DataFrame(schedule_records)
    pivot_df = df.pivot(index='員工', columns='日期', values='班別').fillna('')

    # 確保 output 資料夾存在
    os.makedirs('output', exist_ok=True)

    # 儲存為 Excel（檔名含當天日期）
    today_str = date.today().isoformat()
    filepath = f'output/schedule_{today_str}.xlsx'
    pivot_df.to_excel(filepath)

    print("✅ 排班完成！已輸出至：", filepath)

if __name__ == "__main__":
    main()
